version: "3.9"

services:
  app:
    build:
      context: .
      target: dev
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    command: npm run dev

  prod:
    profiles: ["prod"]
    build:
      context: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    command: npm run start 