name: CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Run ESLint
        run: bun run lint

  typecheck:
    name: Type Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Generate Prisma Client
        run: bunx prisma generate

      - name: Run TypeScript check
        run: bunx tsc --noEmit

  test:
    name: Test
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: sastram_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    env:
      DATABASE_URL: postgresql://postgres:postgres@localhost:5432/sastram_test
      GOOGLE_CLIENT_ID: '${{ secrets.GOOGLE_CLIENT_ID }}'
      GOOGLE_CLIENT_SECRET: '${{ secrets.GOOGLE_CLIENT_SECRET }}'
      GITHUB_CLIENT_ID: '${{ secrets.GITHUB_CLIENT_ID }}'
      GITHUB_CLIENT_SECRET: '${{ secrets.GITHUB_CLIENT_SECRET }}'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Generate Prisma Client
        run: bunx prisma generate

      - name: Run database migrations
        run: bunx prisma db push

      - name: Run tests (if you have any)
        run: bun test || echo "No tests found"

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [lint, typecheck]
    
    env:
      DATABASE_URL: postgresql://postgres:postgres@localhost:5432/sastram_build
      GOOGLE_CLIENT_ID: test_client_id
      GOOGLE_CLIENT_SECRET: test_client_secret
      GITHUB_CLIENT_ID: test_client_id
      GITHUB_CLIENT_SECRET: test_client_secret
      NEXT_PUBLIC_APP_URL: http://localhost:3000

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Generate Prisma Client
        run: bunx prisma generate

      - name: Build application
        run: bun run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: .next/
          retention-days: 7